
\restrict hDeeei4f9ew9QyUKpBaeIiDqiUjbYkUVsMUQiRfT82vDpPfPa2yP20WblYP8QAP


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."dbt_model_changes" (
    "id" bigint NOT NULL,
    "dbt_model_name" "text",
    "pr_html_url" "text",
    "ai_summary" "text",
    "pr_created_at" timestamp with time zone,
    "pr_creator" "text",
    "processed_at" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text")
);


ALTER TABLE "public"."dbt_model_changes" OWNER TO "postgres";


ALTER TABLE "public"."dbt_model_changes" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."dbt_model_changes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."github_pr_merge" (
    "id" integer NOT NULL,
    "pr_number" integer,
    "title" "text",
    "creator" "text",
    "created_at" timestamp with time zone,
    "html_url" "text",
    "repo_owner" "text",
    "repo_name" "text",
    "summary" "text",
    "file_path" "text",
    "processed_at" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text")
);


ALTER TABLE "public"."github_pr_merge" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."github_pr_merge_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."github_pr_merge_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."github_pr_merge_id_seq" OWNED BY "public"."github_pr_merge"."id";



ALTER TABLE ONLY "public"."github_pr_merge" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."github_pr_merge_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."dbt_model_changes"
    ADD CONSTRAINT "dbt_model_changes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."github_pr_merge"
    ADD CONSTRAINT "github_pr_merge_pkey" PRIMARY KEY ("id");





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";








































































































































































GRANT ALL ON TABLE "public"."dbt_model_changes" TO "anon";
GRANT ALL ON TABLE "public"."dbt_model_changes" TO "authenticated";
GRANT ALL ON TABLE "public"."dbt_model_changes" TO "service_role";



GRANT ALL ON SEQUENCE "public"."dbt_model_changes_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."dbt_model_changes_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."dbt_model_changes_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."github_pr_merge" TO "anon";
GRANT ALL ON TABLE "public"."github_pr_merge" TO "authenticated";
GRANT ALL ON TABLE "public"."github_pr_merge" TO "service_role";



GRANT ALL ON SEQUENCE "public"."github_pr_merge_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."github_pr_merge_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."github_pr_merge_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";






























\unrestrict hDeeei4f9ew9QyUKpBaeIiDqiUjbYkUVsMUQiRfT82vDpPfPa2yP20WblYP8QAP

RESET ALL;
